# Generated by Django 4.2 on 2023-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="realname",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
