# Generated by Django 4.2 on 2023-06-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_topic_creation_date"),
        ("accounts", "0002_customuser_realname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favourite_topics",
            field=models.ManyToManyField(to="forum.topic"),
        ),
    ]
