# Generated by Django 4.2 on 2023-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.FileField(null=True, upload_to="files/"),
        ),
    ]
