# Generated by Django 4.2 on 2023-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(max_length=255, null=True, upload_to="images/"),
        ),
    ]
